application:
  server:
    host: "0.0.0.0"
    port: 8080
  environment: development

opentelemetry:
  enabled: true
  metrics_enabled: true
  traces_enabled: true
  collector_endpoint: http://localhost:4317/v1/trace
