get:
  summary: Check if the service is healthy
  operationId: api_v1_monitored_health_get
  description: >-
    This endpoint is used to check if the service is healthy.
  security:
    - BearerAuth: []
  responses:
    "200":
      description: The service is healthy
    "503":
      description: The service is not healthy
  tags:
    - Monitored
