get:
  summary: Check if the service is ready to serve traffic
  operationId: api_v1_monitored_ready_get
  description: >-
    This endpoint is used to check if the service is ready to serve traffic.
    It returns a 200 status code if the service is ready, otherwise it returns
    a 503 status code.
  security:
    - BearerAuth: []
  responses:
    "200":
      description: The service is ready to serve traffic
    "503":
      description: The service is not ready to serve traffic
  tags:
    - Monitored
